repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: a2a447c39b8e87ea803c140b4c58a2b9804e42f8 # frozen: v8.25.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 59fd8610ae21aaf8234f1ef17d43c3ccdee84d16 # frozen: v0.1.29
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck

  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: a804ee07a4c0c0793d3698a8936dea8d79116614 # frozen: v0.15.0
    hooks:
      - id: trivyfs-docker
        args: ["."]
      - id: trivyconfig-docker
        args: ["--severity", "HIGH,CRITICAL", "."]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude_types:
          - markdown

  - repo: https://github.com/executablebooks/mdformat
    rev: ff29be1a1ba8029d9375882aa2c812b62112a593 # frozen: 0.7.22
    hooks:
      - id: mdformat

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: 586c3ea3f51230da42bab657c6a32e9e66c364f0 # frozen: v0.44.0
    hooks:
      - id: markdownlint-fix-docker

  #  - repo: https://github.com/terraform-docs/terraform-docs
  #    rev: 2a6efef6469c3ebb961a3e1388639573d886bfbb # frozen: v0.18.0
  #    hooks:
  #      - id: terraform-docs-system
  #        args:
  #          [
  #            "markdown",
  #            "--output-file",
  #            "README.md",
  #            "--hide-empty",
  #            "--indent",
  #            "3",
  #            ".",
  #          ]

  - repo: https://github.com/golangci/golangci-lint
    rev: 8c14421d29bd005dee63044d07aa897b7d1bf8b0 # frozen: v2.1.5
    hooks:
      - id: golangci-lint-full
        entry: bash -c 'cd test && golangci-lint run --fix'
