formatter: markdown table

version: ">= 0.18.0"

settings:
  anchor: true
  escape: true
  indent: 3
  required: true

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
